### ISSUE TITLE
Game freezes for a few seconds when pausing

### ISSUE THREAD

**Issue by WhitteeDaKitty3** [RayDeeUx/PauseMenuLoop#1]
I have a lower end computer which might be the reason of this happening, but every time I pause the game, it will freeze for a few seconds (in the way where if you click on the screen the "GeometryDash.exe is not responding" message will pop up) and then finally show the pause menu, and it happens every time I pause.

**Comment by RayDeeUx** [comment]
known issue; unfixable until there's a more reliable function from pauselayer that can be hooked
